Docker: Add demo config

diff --git a/docker/development/Dockerfile b/docker/development/Dockerfile
--- a/docker/development/Dockerfile
+++ b/docker/development/Dockerfile
@@ -1,56 +1,3 @@
-#FROM node:18-alpine AS base
-#
-## 1. Install dependencies only when needed
-#FROM base AS deps
-## Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
-#RUN apk add --no-cache libc6-compat
-#
-#WORKDIR /app
-#
-## Install dependencies based on the preferred package manager
-#COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
-#RUN \
-#  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-#  elif [ -f package-lock.json ]; then npm ci; \
-#  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
-#  else echo "Lockfile not found." && exit 1; \
-#  fi
-#
-## 2. Rebuild the source code only when needed
-#FROM base AS builder
-#WORKDIR /app
-#COPY --from=deps /app/node_modules ./node_modules
-#COPY . .
-## This will do the trick, use the corresponding env file for each environment.
-#COPY .env.development.data .env.production
-#RUN yarn build
-#
-## 3. Production image, copy all the files and run next
-#FROM base AS runner
-#WORKDIR /app
-#
-#ENV NODE_ENV=production
-#
-#RUN addgroup -g 1001 -S nodejs
-#RUN adduser -S nextjs -u 1001
-#
-#COPY --from=builder /app/public ./public
-#
-## Automatically leverage output traces to reduce image size
-## https://nextjs.org/docs/advanced-features/output-file-tracing
-#COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
-#COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
-#
-#
-#USER nextjs
-#
-#EXPOSE 3000
-#
-#ENV PORT 3000
-#ENV HOSTNAME localhost
-#
-#CMD ["node", "server.js"]
-
 FROM node:18-alpine
 
 WORKDIR /app
@@ -58,9 +5,9 @@ WORKDIR /app
 # Install dependencies based on the preferred package manager
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 RUN \
-  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+  if [ -f yarn.lock ]; then echo "Install dependencies using yarn." && yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then echo "Install dependencies using npm." && npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then echo "Install dependencies using pnpm." && yarn global add pnpm && pnpm i --frozen-lockfile; \
   else echo "Lockfile not found." && exit 1; \
   fi
 
@@ -74,8 +21,8 @@ COPY . .
 
 # Start Next.js in development mode based on the preferred package manager
 CMD \
-  if [ -f yarn.lock ]; then yarn dev; \
-  elif [ -f package-lock.json ]; then npm run dev; \
-  elif [ -f pnpm-lock.yaml ]; then pnpm dev; \
-  else yarn dev; \
+  if [ -f yarn.lock ]; then echo "Run dev server using yarn." && yarn dev; \
+  elif [ -f package-lock.json ]; then echo "Run dev server using npm." && npm run dev; \
+  elif [ -f pnpm-lock.yaml ]; then echo "Run dev server using pnpm." && pnpm dev; \
+  else echo "Lockfile not found." && exit 1; \
   fi
